FROM ubuntu:20.04

RUN mkdir /app
RUN chmod 777 /app
WORKDIR /app

RUN apt -qq update

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Dhaka

RUN apt -qq install -y nodejs wget

RUN npm install -g torrent-stream-server

EXPOSE 3000
wget "https://raw.githubusercontent.com/devillD-Org/torrent-stream-server/master/start.sh"
CMD ["bash","start.sh"]
